#pragma once

#include <system/SystemBuildConfig.h>

#include CHIP_PROJECT_CONFIG_INCLUDE
#include CHIP_PLATFORM_CONFIG_INCLUDE
#include SYSTEM_PROJECT_CONFIG_INCLUDE
#include SYSTEM_PLATFORM_CONFIG_INCLUDE
#include CHIP_SYSTEM_LAYER_IMPL_CONFIG_FILE

// overrides CHIP_DEVICE_CONFIG_DYNAMIC_ENDPOINT_COUNT in CHIPProjectConfig
//#define CHIP_DEVICE_CONFIG_DYNAMIC_ENDPOINT_COUNT 16
