name: CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '50 4 * * *'

env:
  rust_toolchain: nightly

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Build Essentials
        run: sudo apt-get install git gcc g++ pkg-config libssl-dev libdbus-1-dev libglib2.0-dev libavahi-client-dev ninja-build python3-venv python3-dev python3-pip unzip libgirepository1.0-dev libcairo2-dev libreadline-dev
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.rust_toolchain }}
          components: rustfmt, clippy
      - name: Setup | Std
        run: rustup component add rust-src --toolchain ${{ env.rust_toolchain }}-x86_64-unknown-linux-gnu
      - name: Setup | Default to nightly
        run: rustup default ${{ env.rust_toolchain }}
      - name: Build | Fmt Check
        run: cargo fmt -- --check
#      - name: Build | Clippy
#        run: cargo clippy --features nightly,embedded-svc --no-deps -- -Dwarnings
      - name: Build
        run: cargo build --example on_off
